services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - "13378:80"
    volumes:
      - "${AUDIOBOOKS_PATH}:/audiobooks"
      - "${PODCASTS_PATH}:/podcasts"
      - "${CONFIG_PATH}:/config"
      - "${METADATA_PATH}:/metadata"
    environment:
      - TZ=${TZ}
